apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-tpu-v6-bench
  namespace: production
  labels:
    app: edge-tpu-v6-bench
    version: v1
    component: benchmark-engine
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: edge-tpu-v6-bench
  template:
    metadata:
      labels:
        app: edge-tpu-v6-bench
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: benchmark-engine
        image: ghcr.io/danieleschmidt/edge-tpu-v6-preview-bench/edge-tpu-v6-bench:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8090
          name: metrics
          protocol: TCP
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: EDGE_TPU_API_KEY
          valueFrom:
            secretKeyRef:
              name: edge-tpu-secrets
              key: api-key
        - name: EDGE_TPU_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: edge-tpu-secrets
              key: encryption-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: models-volume
          mountPath: /app/models
          readOnly: true
        - name: temp-volume
          mountPath: /tmp
      volumes:
      - name: config-volume
        configMap:
          name: edge-tpu-config
      - name: models-volume
        persistentVolumeClaim:
          claimName: models-pvc
      - name: temp-volume
        emptyDir:
          sizeLimit: 1Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - edge-tpu-v6-bench
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "edge-tpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: edge-tpu-v6-bench-service
  namespace: production
  labels:
    app: edge-tpu-v6-bench
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: metrics
  selector:
    app: edge-tpu-v6-bench

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-tpu-config
  namespace: production
data:
  config.yaml: |
    benchmark:
      default_mode: "scalable"
      max_workers: 8
      target_latency_ms: 5.0
      target_throughput_fps: 200.0
    
    security:
      enable_validation: true
      max_file_size_mb: 100
      allowed_extensions: [".tflite", ".pb", ".json"]
    
    monitoring:
      enable_metrics: true
      metrics_port: 8090
      log_level: "INFO"
    
    optimization:
      enable_caching: true
      cache_ttl_seconds: 3600
      enable_memory_pooling: true

---
apiVersion: v1
kind: Secret
metadata:
  name: edge-tpu-secrets
  namespace: production
type: Opaque
data:
  # These should be base64 encoded in production
  api-key: ZWRnZS10cHUtdjYtYXBpLWtleQ==  # edge-tpu-v6-api-key
  encryption-key: ZWRnZS10cHUtdjYtZW5jcnlwdGlvbi1rZXk=  # edge-tpu-v6-encryption-key

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: production
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-tpu-v6-bench-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
    - api.edge-tpu-v6-bench.com
    secretName: edge-tpu-v6-bench-tls
  rules:
  - host: api.edge-tpu-v6-bench.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: edge-tpu-v6-bench-service
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-tpu-v6-bench-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-tpu-v6-bench
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: edge-tpu-v6-bench-pdb
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: edge-tpu-v6-bench